[project]
name = "ortmlprod-mar2025-practico-5-model-serving-practico-5-2025"
version = "0.1.0"
description = ""
authors = [
    {name = "Santiago Morón Santos",email = "santimoron001@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi (>=0.136.0,<0.137.0)",
    "uvicorn (>=0.44.0,<0.45.0)",
    "python-multipart (>=0.0.5,<1.0.0)",
    "pydantic (>=2.13.3,<3.0.0)",
    "pydantic-settings (>=2.0.0,<3.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "numpy (>=1.26.0,<2.0.0)",
    "Pillow (>=10.0.0,<11.0.0)",
    "PyYAML (>=6.0,<7.0)",
    "tensorflow (>=2.0.0,<3.0.0)"
]

[project.optional-dependencies]
dev = [
    "pytest (>=9.0.3,<10.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry] 
package-mode = false